name: Build Project
on:
  pull_request:
    branches: ["*"]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "Installing dependencies..."
      - name: Building project
        run: echo "Building project..."
      - name: Force Failure Step
        run: |
          echo "Replace this workflow!"
          exit 1
